config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :states
  resources :social_aids
  devise_for :users
  resources :members
  resources :heads
  resources :users
  root "heads#index"
  get '/reports/eligible_members', to: 'reports#eligible_members'
  get '/reports/clap', to: 'reports#clap'
  get '/reports/homeland', to: 'reports#homeland'
  get '/reports/amor_mayor', to: 'reports#amor_mayor'
  get '/reports/jose_gregorio_hernandez', to: 'reports#jose_gregorio_hernandez'
end

app/models/head.rb
class Head < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_full_name, 
                  against: [:name, :sur_name], 
                  using: {tsearch: {prefix: true}}

  belongs_to :user

  has_many :members, dependent: :destroy
  has_and_belongs_to_many :social_aids

  validates :name, presence: true
  validates :sur_name, presence: true  
  validates :phone_number, presence: true

  def age
    today = Time.now.utc.to_date
    head_birthdate = self.head_birthdate.to_date
    age = today.year - head_birthdate.year
    age -= 1 if (head_birthdate.month > today.month || (head_birthdate.month == today.month && head_birthdate.day > today.day))
    age
  end

  def self.eligible_heads(end_date)
    where("head_birthdate <= ?", end_date - 17.years).order("head_birthdate DESC")
  end
  
end

app/controllers/heads_controller.rb
class HeadsController < ApplicationController
  before_action :set_head, only: %i[ show edit update destroy ]

  # GET /heads or /heads.json
  def index
    @user = current_user
    if params[:query].present?
      @heads = Head.includes(:user)
      .where(user_id: current_user.id).search_by_full_name(params[:query])
      .order(Arel.sql("CAST(substring(home_number from '[0-9]+\\-([0-9]+)') AS INTEGER) ASC"))
    else
      @heads = Head.includes(:user)
      .where(user_id: current_user.id)
      .order(Arel.sql("CAST(substring(home_number from '[0-9]+\\-([0-9]+)') AS INTEGER) ASC"))
    end
    @count = @heads.size
  end

  # GET /heads/1 or /heads/1.json
  def show
    @user = current_user
    @heads = Head.includes(:user).where(user_id: current_user.id)
    @members = Member.includes(:head).where(head_id: @head.id)  
  end

  # GET /heads/new
  def new
    @user = current_user
    @head = Head.new
    @social_aids = SocialAid.all
  end

  # GET /heads/1/edit
  def edit
    @social_aids = SocialAid.all
  end

  # POST /heads or /heads.json
  def create
    @head = Head.new(head_params)

    respond_to do |format|
      if @head.save
        format.html { redirect_to heads_url, notice: "Jefe de Hogar Creado." }
        format.json { render :index, status: :created, location: @head }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @head.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heads/1 or /heads/1.json
  def update
    respond_to do |format|
      if @head.update(head_params)
        format.html { redirect_to heads_url, notice: "Jefe de Hogar Actulizado." }
        format.json { render :index, status: :ok, location: @head }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @head.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heads/1 or /heads/1.json
  def destroy
    @head.destroy

    respond_to do |format|
      format.html { redirect_to heads_url, notice: "Jefe de Hogar Eliminado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_head
      @head = Head.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def head_params
      params.require(:head).permit(:cedula, :name, :sur_name, :head_birthdate, :home_number, :phone_number, :user_id, :disability, :disability_types, :social_aid_ids => [])
    end
end

app/helpers/heads_helper.rb
module HeadsHelper
end

app/views/heads/_form.html.erb
<%= form_with(model: head, data: { turbo_frame: "_top" }) do |form| %>
  <% if head.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(head.errors.count, "error") %> prohibited this head from being saved:</h2>

      <ul>
        <% head.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :cedula, 'Cedula', style: "display: block", class: "form-label" %>
    <%= form.text_field :cedula, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :name, 'Nombre', style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :sur_name, 'Apellido', style: "display: block", class: "form-label" %>
    <%= form.text_field :sur_name, class: 'form-control' %>
  </div>

   <div class="mb-3">
    <%= form.label :home_number, '# casa', style: "display: block", class: "form-label" %>
    <%= form.text_field :home_number, class: 'form-control' %>
  </div>

   <div class="mb-3">
    <%= form.label :phone_number, 'Teléfono', style: "display: block", class: "form-label" %>
    <%= form.text_field :phone_number, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :head_birthdate, 'Fecha de Nacimiento', style: "display: block", class: "form-label" %>
    <%= form.date_field :head_birthdate %>
  </div>
  <div class="mb-3">
    <%= form.label :disability, '¿Tiene alguna discapacidad?', style: "display: block", class: "form-label" %>
    <%= form.check_box :disability %>
  </div>
  
  <div class="mb-3">
    <%= form.label :disability_types, 'Tipo de discapacidad', style: "display: block", class: "form-label" %>
    <%= form.text_field :disability_types, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :social_aids, "Ayuda Social" %>
      <% SocialAid.all.each do |social_aid| %>
        <div class="form-check">
           <%= check_box_tag "head[social_aid_ids][]", social_aid.id, @head.social_aid_ids.include?(social_aid.id) %>
           <%=      label_tag "head[social_aid_ids][]", social_aid.name %>
        </div>
      <% end %>      
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div>
    <%= form.submit 'Guardar', class:"btn btn-primary" %>
    
  </div>
<% end %>

app/views/heads/_head.html.erb
<tr id="<%= dom_id head %>"> 
  <td>
    <%= head.cedula %>
  </td>

  <td>
    <%= head.name %> <%= head.sur_name %>
  </td>
  <td>
    <%= link_to "Editar", edit_head_path(head), data: { turbo_frame: "modal-edit-heads" } %>
  </td>

  <td>
  <%= link_to "Ver", head %>
  </td>

  <td>
  <%= button_to "Eliminar", head, method: :delete, data: {"turbo-confirm": '¿Quieres eliminar éste Jefe de Hogar?'} , class: "btn btn-danger" %>
  </td>  
</tr>

app/views/heads/edit.html.erb
<%= turbo_frame_tag "modal-edit-heads" do %>
  <div class="my-modal">
    <div class="cancel-button rounded-5 col-md-6 container text-bg-light p-3">
    <h2 class='text-center'>Editar Jefe de hogar</h2>  
    <%= render "form", head: @head %>  
    <br>
    <%= render partial: "shared/close_button" %>
  </div>
<% end %>

app/views/heads/index.html.erb
<div class="rounded-5 container text-bg-light p-3">

<h2 class='text-center'>Jefes de Hogares: <%= @count %></h2>
<div id="search-bar">
   <%= form_tag(heads_path, method: :get) do %>
      <%= text_field_tag :query, params[:query], placeholder: "Buscar jefes de hogar" %>
      <%= submit_tag "Buscar" %>
   <% end %>
</div>
<div id="heads" class="overflow">
<table class="table table-striped">
  <thead>
    <tr>      
      <th scope="col">Cedula</th>
      <th scope="col">Nombre</th>
      <th scope="col">Editar</th>
      <th scope="col">Hogar</th>
      <th scope="col">Eliminar</th>
    </tr>
  </thead>
  <tbody>
    <% @heads.each do |head| %>
      <%= render head %>   
    <% end %>
  </tbody>
</table>
</div>
<%= link_to "Nuevo Jefe de hogar", new_head_path, data: { turbo_frame: "new-head" } %>
</div>

app/views/heads/new.html.erb
<%= turbo_frame_tag "new-head" do %>
  <div class="my-modal">
    <div class="rounded-5 col-md-6 container text-bg-light p-3">
      <div>
        <h1>Nuevo Jefe de Hogar</h1>    
        <%= render "form", head: @head %>    
        <br>    
        <%= render partial: "shared/close_button" %>
      </div>
    </div>
  </div>
<% end %>

app/views/heads/show.html.erb
<div class="container text-bg-light p-3 rounded-5">

<h2 class='login-h1 red-border-b text-center'>Hogar de <%= @head.name%> <%= @head.sur_name%></h2>

<div id="members"  class="overflow">
  <table class="table table-striped">
  <thead>
    <tr>      
      <th scope="col">Cedula</th>
      <th scope="col">Nombre</th>
      <th scope="col">Parentesco</th>
      <th scope="col">Editar</th>      
      <th scope="col">Eliminar</th>
    </tr>
  </thead>
    <tbody>
      <% @members.each do |member| %>
        <%= render member %>
      <% end %>
    </tbody>
  </table>
</div>
<div> 
  <%= link_to "Regresar", heads_path %>  |  
  <%= link_to "Nuevo Integrante", new_member_path(head_id: @head.id), data: { turbo_frame: "new-member" } %> 
</div>
</div>