config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :states
  resources :social_aids
  devise_for :users
  resources :members
  resources :heads
  resources :users
  root "heads#index"
  get '/reports/eligible_members', to: 'reports#eligible_members'
  get '/reports/clap', to: 'reports#clap'
  get '/reports/homeland', to: 'reports#homeland'
  get '/reports/amor_mayor', to: 'reports#amor_mayor'
  get '/reports/jose_gregorio_hernandez', to: 'reports#jose_gregorio_hernandez'
end

app/models/state.rb
class State < ApplicationRecord
    has_many :cities
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: %i[ show edit update destroy ]

  # GET /states or /states.json
  def index
    @user = current_user
    @states = State.all    
  end

  # GET /states/1 or /states/1.json
  def show
    @user = current_user
  end

  # GET /states/new
  def new
    @state = State.new
    @user = current_user
  end

  # GET /states/1/edit
  def edit
    @user = current_user
  end

  # POST /states or /states.json
  def create  
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to state_url(@state), notice: "State was successfully created." }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1 or /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to state_url(@state), notice: "State was successfully updated." }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1 or /states/1.json
  def destroy
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url, notice: "State was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def state_params
      params.require(:state).permit(:state_name)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_with(model: state) do |form| %>
  <% if state.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
        <% state.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :state_name, style: "display: block" %>
    <%= form.text_field :state_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/states/_state.html.erb
<tr id="<%= dom_id state %>">
  <td>
    <%= state.id %>
  </td>

  <td>
    <%= state.state_name %>
  </td>
  <td>
    <%= link_to "Editar", edit_state_path(state) %>
  </td>

  <td>
  <%= link_to "Ver", cities_path(state_id: state.id) %>
  </td>

  <td>
  <%= button_to "Eliminar", state, method: :delete, data: {"turbo-confirm": '¿Quieres eliminar éste Estado?'} , class: "btn btn-danger" %>
  </td>  
</tr>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Show this state", @state %> |
  <%= link_to "Back to states", states_path %>
</div>

app/views/states/index.html.erb
<div class="rounded-5 container text-bg-light p-3">

<h2 class='text-center'>Jefes de Hogares: <%= @count %></h2>

<div id="states" class="overflow">
<table class="table table-striped">
  <thead>
    <tr>      
      <th scope="col">id</th>
      <th scope="col">Estado</th>
      <th scope="col">Editar</th>
      <th scope="col">Ciudades</th>
      <th scope="col">Eliminar</th>
    </tr>
  </thead>
  <tbody>
    <% @states.each do |state| %>
      <%= render state %>   
    <% end %>
  </tbody>
</table>
</div>
<%= link_to "New state", new_state_path %>
</div>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Back to states", states_path %>
</div>

app/views/states/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @state %>

<div>
  <%= link_to "Edit this state", edit_state_path(@state) %> |
  <%= link_to "Back to states", states_path %>

  <%= button_to "Destroy this state", @state, method: :delete %>
</div>