config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :states
  resources :social_aids
  devise_for :users
  resources :members
  resources :heads
  resources :users
  root "heads#index"
  get '/reports/eligible_members', to: 'reports#eligible_members'
  get '/reports/clap', to: 'reports#clap'
  get '/reports/homeland', to: 'reports#homeland'
  get '/reports/amor_mayor', to: 'reports#amor_mayor'
  get '/reports/jose_gregorio_hernandez', to: 'reports#jose_gregorio_hernandez'
end

app/models/social_aid.rb
class SocialAid < ApplicationRecord
    has_and_belongs_to_many :heads
end

app/controllers/social_aids_controller.rb
class SocialAidsController < ApplicationController
  before_action :set_social_aid, only: %i[ show edit update destroy ]

  # GET /social_aids or /social_aids.json
  def index
    @social_aids = SocialAid.all
  end

  # GET /social_aids/1 or /social_aids/1.json
  def show
  end

  # GET /social_aids/new
  def new
    @social_aid = SocialAid.new
  end

  # GET /social_aids/1/edit
  def edit
  end

  # POST /social_aids or /social_aids.json
  def create
    @social_aid = SocialAid.new(social_aid_params)

    respond_to do |format|
      if @social_aid.save
        format.html { redirect_to social_aid_url(@social_aid), notice: "Social aid was successfully created." }
        format.json { render :show, status: :created, location: @social_aid }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @social_aid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /social_aids/1 or /social_aids/1.json
  def update
    respond_to do |format|
      if @social_aid.update(social_aid_params)
        format.html { redirect_to social_aid_url(@social_aid), notice: "Social aid was successfully updated." }
        format.json { render :show, status: :ok, location: @social_aid }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @social_aid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /social_aids/1 or /social_aids/1.json
  def destroy
    @social_aid.destroy

    respond_to do |format|
      format.html { redirect_to social_aids_url, notice: "Social aid was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_social_aid
      @social_aid = SocialAid.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def social_aid_params
      params.require(:social_aid).permit(:name, :description)
    end
end

app/helpers/social_aids_helper.rb
module SocialAidsHelper
end

app/views/social_aids/_form.html.erb
<%= form_with(model: social_aid) do |form| %>
  <% if social_aid.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(social_aid.errors.count, "error") %> prohibited this social_aid from being saved:</h2>

      <ul>
        <% social_aid.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/social_aids/_social_aid.html.erb
<div id="<%= dom_id social_aid %>">
  <p>
    <strong>Name:</strong>
    <%= social_aid.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= social_aid.description %>
  </p>

</div>

app/views/social_aids/edit.html.erb
<h1>Editing social aid</h1>

<%= render "form", social_aid: @social_aid %>

<br>

<div>
  <%= link_to "Show this social aid", @social_aid %> |
  <%= link_to "Back to social aids", social_aids_path %>
</div>

app/views/social_aids/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Social aids</h1>

<div id="social_aids">
  <% @social_aids.each do |social_aid| %>
    <%= render social_aid %>
    <p>
      <%= link_to "Show this social aid", social_aid %>
    </p>
  <% end %>
</div>

<%= link_to "New social aid", new_social_aid_path %>

app/views/social_aids/new.html.erb
<h1>New social aid</h1>

<%= render "form", social_aid: @social_aid %>

<br>

<div>
  <%= link_to "Back to social aids", social_aids_path %>
</div>

app/views/social_aids/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @social_aid %>

<div>
  <%= link_to "Edit this social aid", edit_social_aid_path(@social_aid) %> |
  <%= link_to "Back to social aids", social_aids_path %>

  <%= button_to "Destroy this social aid", @social_aid, method: :delete %>
</div>