config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :states
  resources :social_aids
  devise_for :users
  resources :members
  resources :heads
  resources :users
  root "heads#index"
  get '/reports/eligible_members', to: 'reports#eligible_members'
  get '/reports/clap', to: 'reports#clap'
  get '/reports/homeland', to: 'reports#homeland'
  get '/reports/amor_mayor', to: 'reports#amor_mayor'
  get '/reports/jose_gregorio_hernandez', to: 'reports#jose_gregorio_hernandez'
end

app/views/layouts/_modals.html.erb
<%= turbo_frame_tag "modal-edit-heads" %>
<%= turbo_frame_tag "new-head" %>
<%= turbo_frame_tag "new-member" %>
<%= turbo_frame_tag "edit-member" %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
    <%= image_tag('logo.png', style: "width: 100px; height: 75px;")%>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Inicio", root_path, class:"nav-link text-light active"%>
        </li>        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Reportes
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Votantes", reports_eligible_members_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "CLAP", reports_clap_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Hogares de la patria", reports_homeland_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Amor mayor", reports_amor_mayor_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "José Gregorio Hernández", reports_jose_gregorio_hernandez_path, class: "dropdown-item" %></li>          
          </ul>
        </li> 
        <li class="nav-item">
          <%= link_to "Perfil de usuario", user_path(@user), class:"nav-link text-light active"%>
        </li>       
      </ul>
      <div class="d-flex">
        <%= button_to 'Salir', destroy_user_session_path, method: :delete, data: {"turbo-confirm": '¿Desea cerrar sesión?'}, class: "btn btn-primary" %>     
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestionComunitaria</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="text-bg-secondary p-3">
    <% if user_signed_in? %>   
      <%= render "layouts/navbar" %>
    <% end %>
    <div>
    <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
    <%= render partial: "layouts/modals" %>
  </body>
</html>